//! Shared token-endpoint plumbing: the raw POST, structured error decoding,
//! and turning a token response into a [`CachedSession`]. Authorization-code,
//! device-code and refresh flows all funnel through here so retry/error
//! handling (`authorization_pending`, `slow_down`, ...) is decoded once.

use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result};
use serde::Deserialize;

use super::OidcMetadata;
use crate::{cache::CachedSession, config::OauthConfig, redacted::Redacted};

#[derive(Debug, Deserialize)]
pub struct RawTokenResponse {
    pub access_token: Redacted<String>,
    pub refresh_token: Option<Redacted<String>>,
    pub expires_in: Option<u64>,
}

#[derive(Debug, Deserialize, Default)]
struct TokenErrorBody {
    error: Option<String>,
    // Deliberately not deserialized into a field: `error_description` is
    // free text from the authorization server, and an RFC 8693/RFC 6749
    // error response can echo submitted input (e.g. the subject token on a
    // token-exchange request, see `oauth::exchange`) back verbatim -- the
    // same reasoning `oauth::mod::revoke` already applies to a revocation
    // error body. Extra JSON fields are ignored by default (no
    // `#[serde(deny_unknown_fields)]`), so simply not naming the field here
    // is enough to keep it out of this binary entirely, not just out of
    // `Display`.
}

/// A structured token-endpoint failure. Kept distinct from `anyhow::Error`
/// so the device-code poll loop can match on `code` (`authorization_pending`,
/// `slow_down`) instead of substring-matching a formatted message.
#[derive(Debug)]
pub struct TokenEndpointError {
    pub status: reqwest::StatusCode,
    /// A fixed OAuth2 enum (`invalid_grant`, `invalid_client`, ...) -- safe
    /// to print, and what actually makes an error actionable.
    pub code: Option<String>,
    /// Diagnostic detail generated by THIS binary (a transport failure, or a
    /// success-status response that failed to parse) -- never populated from
    /// the authorization server's own `error_description`. See
    /// [`TokenErrorBody`]'s doc for why that free-text field is never even
    /// deserialized.
    pub description: Option<String>,
}

impl std::fmt::Display for TokenEndpointError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "token endpoint returned {} ({})",
            self.status,
            self.code.as_deref().unwrap_or("unknown_error"),
        )?;
        if let Some(description) = &self.description {
            write!(f, ": {description}")?;
        }
        Ok(())
    }
}

impl std::error::Error for TokenEndpointError {}

fn transport_error(description: String) -> TokenEndpointError {
    TokenEndpointError {
        status: reqwest::StatusCode::INTERNAL_SERVER_ERROR,
        code: None,
        description: Some(description),
    }
}

pub async fn request(
    http: &reqwest::Client,
    token_endpoint: &str,
    params: &[(&str, &str)],
) -> Result<RawTokenResponse, TokenEndpointError> {
    let response = http
        .post(token_endpoint)
        .form(params)
        .send()
        .await
        .map_err(|error| transport_error(format!("calling {token_endpoint}: {error}")))?;

    let status = response.status();
    let body = response
        .text()
        .await
        .map_err(|error| transport_error(format!("reading response body: {error}")))?;

    if !status.is_success() {
        let parsed: TokenErrorBody = serde_json::from_str(&body).unwrap_or_default();
        return Err(TokenEndpointError {
            status,
            code: parsed.error,
            // Deliberately not the body: see `TokenErrorBody`'s doc.
            description: None,
        });
    }

    serde_json::from_str(&body).map_err(|error| TokenEndpointError {
        status,
        code: None,
        description: Some(format!("parsing token response: {error}")),
    })
}

pub fn into_session(config: &OauthConfig, response: RawTokenResponse) -> Result<CachedSession> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .context("reading system clock")?
        .as_secs();
    // The EFFECTIVE lifetime, not the raw `expires_in`: a server that omits
    // the field is treated as issuing 60s tokens for `expires_at`, and
    // `crate::freshness`'s cap has to reason about the same number this
    // session was actually stamped with.
    let lifetime_secs = response.expires_in.unwrap_or(60);
    Ok(CachedSession {
        issuer: config.issuer.clone(),
        client_id: config.client_id.clone(),
        access_token: response.access_token,
        refresh_token: response.refresh_token,
        expires_at: now.saturating_add(lifetime_secs),
        lifetime_secs: Some(lifetime_secs),
    })
}

pub async fn refresh(
    http: &reqwest::Client,
    metadata: &OidcMetadata,
    config: &OauthConfig,
    refresh_token: &str,
) -> Result<CachedSession> {
    let mut params = vec![
        ("grant_type", "refresh_token"),
        ("refresh_token", refresh_token),
        ("client_id", config.client_id.as_str()),
    ];
    if let Some(audience) = &config.audience {
        params.push(("audience", audience.as_str()));
    }

    let response = request(http, &metadata.token_endpoint, &params).await?;
    let mut session = into_session(config, response)?;
    // Keycloak rotates refresh tokens on every use; if this particular
    // response omitted one, keep using the one we already had rather than
    // discarding a still-valid rotation chain.
    if session.refresh_token.is_none() {
        session.refresh_token = Some(Redacted::new(refresh_token.to_owned()));
    }
    Ok(session)
}
