{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-env
  labels:
    app: {{ .Values.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeRef }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-env
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecret.saltProperty }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: {{ .Values.externalSecret.saltProperty }}
{{- end }}
